name: app

type: php:8.2

build:
    flavor: none

relationships:
    database: "database:mysql"

web:
    locations:
        "/":
            root: "public"
            index:
                - index.php
            scripts: true
            allow: true
            passthru: "/index.php"
    commands:
        start: php artisan serve
    upload_max_filesize: "2M"
    post_max_size: "3M"
    client_max_body_size: "3M"

disk: 2048

mounts:
    'storage/app/public': 
        source: local
        source_path: 'storage'

hooks:
    build: |
        set -e
        composer install --no-dev --prefer-dist --optimize-autoloader
        php artisan storage:link
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
    deploy: |
        php artisan migrate --force
        php artisan storage:link